name: Forum-Bridge
author:
    - Favorlock
main: com.favorlock.ForumBridge.ForumBridge
version: 1.0.4b
database: false
description: A forum bridge plugin for Bukkit.
commands:
  bbb:
    description: Bulletin Board Bridge help menu.
    usage: |
           Usage: /<command>
  bbbversion:
    description: Bulletin Board Bridge version command.
    usage: |
           Usage: /<command>
  sync:
    description: Bulletin Board Bridge sync command.
    usage: |
           Usage: /<command>
    permission: bbb.sync
  resync:
    description: Bulletin Board Bridge resync command.
    usage: |
           Usage: /<command>
  fsync:
    description: Bulletin Board Bridge moderation command.
    usage: |
           Usage: /<command>
  fsyncall:
    description: Bulletin Board Bridge moderation command.
    usage: |
           Usage: /<command>
  fban:
    description: Bulletin Board Bridge moderation command.
    usage: |
           Usage: /<command>
  funban:
    description: Bulletin Board Bridge moderation command.
    usage: |
           Usage: /<command>
  fpromote:
    description: Bulletin Board Bridge promotion command.
    usage: |
           Usage: /<command>
  fdemote:
    description: Bulletin Board Bridge demotion command.
    usage: |
           Usage: /<command>
  frank:
    description: Bulletin Board Bridge forum rank changing command.
    usage: |
           Usage: /<command>
  fusername:
    description: Bulletin Board Bridge forum username loForumBridgeup command.
    usage: |
            Usage: /<command>
permissions:
  bbb.*:
    description: Gives access to all commands
    children:
      bbb.sync: true
      bbb.demote: true
      bbb.promote: true
      bbb.forceall: true
      bbb.force: true
      bbb.unban: true
      bbb.ban: true
      bbb.fusername: true
  bbb.sync:
    description: Allow the usage of the /sync command
    default: true
  bbb.demote:
    description: Allow the usage of the /fdemote command
    default: op
  bbb.promote:
    description: Allow the usage of the /fpromote command
    default: op
  bbb.forceall:
    description: Allow the usage of the /fsyncall command
    default: op
  bbb.force:
    description: Allow the usage of the /fsync command
    default: op
  bbb.unban:
    description: Allow the usage of the /funban command
    default: op
  bbb.ban:
    description: Allow the usage of the /fban command
    default: op
  bbb.fusername:
    description: Allow the usage of the /fusername command
    default: op
    